services:
  - type: web
    name: interview-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    autoDeploy: true